### PR TITLE
Add unit test and fix typo

### PR DESCRIPTION
**Pull request by 0xh3xa**
1. Fix typo
2. Add checking for Null pointer exception 
3. Add unit test classes: DomainAssemblerTest, ResourceAssemblerTest

### CODE REVIEW

**Comment by 0xh3xa** [comment]
converage

**Comment by marcosvidolin** [comment]
Hi @ahmadmoawad 

Good job with all tests and fixes.
Can you please check the "Codacy" fails and add .ds_store files to be ignored.

Thanks

**Review by marcosvidolin — APPROVED** [review]
😃

**Comment by marcosvidolin** [comment]
@MunGell Please review

**Comment by MunGell** [comment]
LGTM :)

**Pull request merged**
